name: Node.js CI
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  test:
    strategy:
      matrix:
        node: [16.x, 17.x, 18.x, 19.x, 20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      if: matrix.node != '14.x'
      with:
        version: '9'

    - run: pnpm install --no-frozen-lockfile
      if: matrix.node != '14.x'

    - run: npm install
      if: matrix.node == '14.x'

    - run: npm run build
    - run: npm run build-docs
    - run: npm run cover:test
      if: matrix.os != 'windows-latest'
    - run: npm run cover:test-no-fse
      if: matrix.os == 'windows-latest'
