name: Node.js CI
on:
  push:
    branches: master
  pull_request:

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  test:
    strategy:
      matrix:
        node: [14.x, 16.x, 18.x, 19.x, 20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598
      uses: pnpm/action-setup@v2.4.0
      with:
        # Version of pnpm to install
        # version: # optional
        # Where to store pnpm files
        # dest: # optional, default is ~/setup-pnpm
        # If specified, run `pnpm install`
        run_install: true # optional, default is null
        # File path to the package.json to read "packageManager" configuration
        # package_json_file: # optional, default is package.json
        # When set to true, @pnpm/exe, which is a Node.js bundled package, will be installed, enabling using pnpm without Node.js.
        # standalone: # optional, default is false

    - run: npm run build
    - run: npm run build-docs
    - run: npm run test
      if: ${{ matrix.os }} != 'windows-latest'
    - run: npm run test-no-fse
      if: ${{ matrix.os }} == 'windows-latest'
